name: "Setup Cpp"
description: "Install all the tools required for building and testing C++/C projects."
author: "Amin Yahyaabadi"

inputs:
  compiler:
    description: "The compiler to use and its optional version separated by - e.g. llvm-13.0.0"
    required: false
  architecture:
    description: "The CPU architecture"
    required: false
  llvm:
    description: "The llvm version to install"
    required: false
  gcc:
    description: "The gcc version to install"
    required: false
  msvc:
    description: "The msvc version to install"
    required: false
  vcvarsall:
    description: "If should run vcvarsall?"
    required: false
  cmake:
    description: "The cmake version to install."
    required: false
  ninja:
    description: "The ninja version to install."
    required: false
  conan:
    description: "The conan version to install."
    required: false
  make:
    description: "The make version to install."
    required: false
  task:
    description: "The task version to install."
    required: false
  vcpkg:
    description: "The vcpkg version to install."
    required: false
  meson:
    description: "The meson version to install."
    required: false
  gcovr:
    description: "The gcovr version to install."
    required: false
  python:
    description: "The python version to install."
    required: false
  ccache:
    description: "The ccache version to install."
    required: false
  doxygen:
    description: "The doxygen version to install."
    required: false
  graphviz:
    description: "The graphviz version to install."
    required: false
  cppcheck:
    description: "The cppcheck version to install."
    required: false
  clangtidy:
    description: "The clang-tidy version to install."
    required: false
  clangformat:
    description: "The clang-format version to install."
    required: false
  opencppcoverage:
    description: "The opencppcoverage version to install."
    required: false
  kcov:
    description: "The kcov version to install."
    required: false
  sevenzip:
    description: "The 7z version to install."
    required: false
  nala:
    description: 'The nala version to install ("" or "legacy").'
    required: false

runs:
  using: "node12"
  main: "dist/setup_cpp.js"

branding:
  icon: "award"
  color: "blue"
